#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=$(pwd)           # dotfiles directory
olddir=~/Dotfiles_old    # old dotfiles backup directory
files="bashrc bash_aliases vimrc vim git-completion.bash" # list of files/folders to symlink in homedir
:
##########

# clear the terminal
printf "\ec"

# install the git submodule so I have my vim plugins
git submodule update --init --recursive

# remove dotfiles_old in homedir
if [ -d "$olddir" ]; then
    echo "Removing ~$olddir"
    rm -rf $olddir
fi

# create dotfiles_old in homedir
echo "Creating ~$olddir for backup of any existing dotfiles"
mkdir -p $olddir

# change to the dotfiles directory
echo "Changing to $dir"
cd $dir

# move any existing dotfiles in homedir to Dotfiles_old directory, then copy files
for file in $files; do
    if ! [ -L ~/.$file ] && [ -e ~/.$file ]; then
        echo "Moving ~/.$file to $olddir/.$file"
        mv ~/.$file $olddir
#    else
#        echo "Removing existing ~/.$file"
#        rm ~/.$file
    fi

    echo "Copying $dir/$file to ~/$file"
    cp -R $dir/$file ~/.$file
done

# reload bashrc so everything takes effect
echo "Reloading .bashrc"
source ~/.bashrc
